### PR TITLE
Added support for live code generation

### PR DESCRIPTION
**Pull request by Xaptor**

### CODE REVIEW

**Comment by nbudin** [comment]
Hi @Xaptor, thanks for the PR!  If I understand correctly, the intent of this is to enable code generation for languages other than XML (such as JavaScript, Python, PHP, etc.), right?  I like the way you did this generically by exposing a `workspaceDidChange` prop so we don't need separate props for every language.

Potentially, this eliminates the need for `xmlDidChange` (because the user can now implement that functionality on top of `workspaceDidChange`), so I think we should deprecate that prop in favor of this one.

Would you mind adding the new prop to the readme, as well as a deprecation warning about `xmlDidChange`?  Thank you, and thanks for your code!

**Comment by Xaptor** [comment]
Hi @nbudin, yes it is to enable clientside code generation for javascript, php etc.
You are right this eliminates the xmlDidChange callback so i've removed that function from the example and put a deprecation warning as a console.error into the BlockyEditor componentdidMount function, so it will be triggered only once. Is that the way you have thought of?

**Comment by nbudin** [comment]
@Xaptor: Yes, that seems like a good way to do it.  Could you also add a check to make sure `console` and `console.error` exist before doing that statement?  (IIRC, some environments don't include those so we don't want to accidentally break those.)

**Comment by Xaptor** [comment]
@nbudin I've added a check but it is untested. Can you tell me an environment where they don't exist?

**Comment by nbudin** [comment]
@Xaptor: thanks!  One such environment is IE8 (without the developer tools window open).  See this StackOverflow thread for a discussion of it: https://stackoverflow.com/questions/3326650/console-is-undefined-error-for-internet-explorer

Based on that thread, the check is still going to error out in IE8.  It looks like `typeof console !== 'undefined'` might do it, though?

**Comment by Xaptor** [comment]
@nbudin I've added the typeof check. It looks like React is not supporting IE8 (https://reactjs.org/blog/2016/01/12/discontinuing-ie8-support.html) so i don't know if it will have any benefit.

**Comment by nbudin** [comment]
Cool, thanks for your work!  I'll pull this in.

We're preparing an upcoming release to support React 16, so I think I'd like to try to release this along with that since that'll be a major version bump in any case.

**Pull request merged**
